<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'username'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function (User $user){
//            $p1=new Profile();
//            $p1->image='';
//            $p1->title='';
//            $p1->url='';
//            $p1->description='';
//            $user->profile=$p1;
//
//                $user->save();

            $user->profile()->create([
                'title' => $user->username,
            ]);
        });
    }

    public function profile(){
        return $this->hasOne(Profile::class);
    }

    public function posts(){
        return $this->hasMany(Post::class)->orderBy('created_at','desc');
    }
    public function following(){
        return $this->belongsToMany($this,'followers','following','follower');
    }
    public function followers(){
        return $this->belongsToMany($this,'followers','follower','following');
    }
}
